name: Vehicle Data Collector

on:
  schedule:
    - cron: "0 3 * * *" # Runs daily at 3 AM UTC
  workflow_dispatch: # Allow manual trigger

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python fetch_data.py

      - name: Commit & Push data
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add data/vehicle_data.csv
          git commit -m "Daily data update $(date -u)" || echo "No changes to commit"
          git push
